// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

// DATABASE_URL is required - use DIRECT_URL if provided, otherwise use DATABASE_URL
// DIRECT_URL is used for migrations (direct connection), DATABASE_URL for queries (can be pooled)
const databaseUrl = process.env["DIRECT_URL"] || process.env["DATABASE_URL"];

if (!databaseUrl) {
  throw new Error(
    "DATABASE_URL or DIRECT_URL environment variable is not set. Please add it to your .env file.\n" +
    "Example: DATABASE_URL=\"postgresql://postgres:[PASSWORD]@[HOST].supabase.co:5432/postgres?schema=public\"\n" +
    "Or use DIRECT_URL for migrations and DATABASE_URL for queries (connection pooling)"
  );
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
